apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: demo-java
build:
  artifacts:
    - image: ghuang/demo-java
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: "css/**/*.css"
          dest: "app/"
deploy:
  kubectl:
    manifests:
    - kube/dev-java.yaml
