---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: hello-java
  namespace: demo
spec:
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: ghuang/demo-java
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
  selector:
    app: hello-java
---
#apiVersion: v1
#kind: Route
#metadata:
#  name: hello-java
#spec:
#  to:
#    kind: Service
#    name: hello-java
