on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: jenkinsfile-runner-prepackaged
      uses: ./.github/actions/jenkinsfile-runner-github-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
